----CREATE DATABASE CANDYSHOP
----USE CANDYSHOP


----CREATE TABLE CLIENTE(
----	idCliente INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
----	CPF BIGINT UNIQUE NOT NULL,
----	Nome_CLi VARCHAR (50) NOT NULL,
----	Sexo CHAR (1),
----	Dat_Nasc DATE,
----	idStatus_Cli CHAR(1)
----)

----CREATE TABLE TIPO_PRODUTO(
----	idTipoProduto INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
----	NomeTipoProduto VARCHAR(50) NOT NULL
----)


----CREATE TABLE MARCA(
----	idMarca INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
----	NomeMarca VARCHAR(50) NOT NULL
----)

--CREATE TABLE PRODUTO(
--	idProduto INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--	Nome_Prod VARCHAR(50) NOT NULL,
--	idTipoProd INT REFERENCES TIPO_PRODUTO (idTipoProduto) NOT NULL,
--	idMarca INT REFERENCES MARCA (idMarca) NOT NULL,
--	ValorVenda DECIMAL(15,2)

--)


--CREATE TABLE VENDA(
--	idVenda INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--	idCliente INT REFERENCES CLIENTE (idCliente) NOT NULL,
--	DataVenda DATE NOT NULL,
--	DataPag DATE
--)

--CREATE TABLE ITEM_VENDA(
--	idItemVenda INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--	idProduto INT REFERENCES [dbo].[PRODUTO] (idProduto) NOT NULL,
--	idVenda INT REFERENCES VENDA (idVenda) NOT NULL,
--	Quantidade INT NOT NULL
--)

--CREATE TABLE COMPRA(
--	idCompra INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
--	idProduto INT REFERENCES PRODUTO (idProduto) NOT NULL,
--	QuantidadeCompra INT NOT NULL,
--	ValorCompra DECIMAL(15,2) NOT NULL
--)



