--03- Popule seu BD.

INSERT INTO MUSICO(NOMEMUS,IDRES)
VALUES ('ROGER HOGDSON',1),
	   ('RICK DAVIES',2),                    
	   ('JOHN HELLIWELL',2),   
	   ('AXL ROSE',3),												
	   ('KURT COBAIN',4),
	   ('CAZUZA',5),
	   ('RENATO RUSSO',5),
	   ('ROBERTO CARLOS',5),
	   ('PITTY',4),
	   ('VANESSA DA MATA',3)

INSERT INTO RESIDENCIA(ENDERECO,TELEFONE)
VALUES('RUA VERONICA 275','3477-8901'),
	  ('RUA PEDREGULHO 554','3409-0872'),
	  ('RUA ANTONIO BERNARDES PINTO 775','3721-7888'),
	  ('RUA GERALDO FLAUSINO SENNE 1171','3721-7996'),
	  ('RUA MARIA PATROCINIA DE CARVALHO 663','3409-7995')

INSERT INTO INSTRUMENTO(NOMEINS)  
VALUES ('GUITARRA'),
	   ('CONTRABAIXO'),
	   ('FLAUTA DOCE'),
	   ('BATERIA'),
	   ('TECLADO'),
	   ('PIANO'),
	   ('SAXOFONE'),
	   ('TRIANGULO'),
	   ('TAMBOR'),
	   ('FLAUTA TRANSVERSAL')

INSERT INTO TOCA(IDMUS,IDINS)
VALUES		(1,2),
			(3,5),
			(3,4),
			(1,3),
			(7,6),
			(9,4),
			(6,7),
			(3,3),
			(2,2),
			(10,10),
			(10,5),
			(4,5),
			(6,6),
			(5,3),
			(9,8)

INSERT INTO ALBUM(TITULO,FORMATO,DATA,IDMUS)
VALUES		('NEVERMORE','CD','01-08-1999',2),
			('SÓ SUCESSOS','K7','08-06-1987',1),
			('A MUSA DO VERÃO','CD','04-12-1998',4),
			('SÓ PRA CONTRARIAR','K7','07-12-1985',5),
			('AMOR I LOVE YOU','CD','01-04-2004',4),
			('SEM IDEIA PRA TITULO','CD','04-02-2003',1),
			('ACHO QUE JA TA BOM','CD','08-09-2004',5)


INSERT INTO MUSICA(TMUS,AUTOR,IDALBUM)
VALUES		('CANSEI','PEDRO DE LARA',1),
			('DE FAZER','MARCOS PAULO',2),
			('BANCO DE DADOS','KELLY DOOR',3),
			('ACHO QUE','MARIA SILVA',4),
			('VOU LÁ','JOAO SILVA',5),
			('COMER','JEAN TADEU',6),
			('O BOLO','SILVANA',7),
			('PORÉM','MARCIO ALVES',2),
			('EU ACHO','PEDRO CARDOSO',5),
			('QUE EU','JOSEFINA',5),
			('NÃO FIZ','MARCELA',1),
			('O BOLO AINDA','DANILO ALVES',3),
			('ENTÃO PRECISO','MARCELA ABREU',5),
			('VER RECEITA','CARLOS SILVA',3),
			('NA INTERNET','JOSÉ EURIPEDES',5),
			('EU SÓ NÃO SEI','MARTA PAULA',4),
			('SE VAI FICAR BOM','JOAO CARLOS',3),
			('JÁ QUE','MARIA DA DORES',7),
			('EU NAO TENHO','EURIPA',3),
			('EXPERIÊNCIA','MILADY',2),
			('NA COZINHA','INÁCIO',2)

--04- Listar título do álbum e nome do músico de todos os álbuns.
SELECT TITULO,NOMEMUS
FROM ALBUM A INNER JOIN MUSICO M ON 
A.IDMUS = M.IDMUS


--05- Listar nome da música e álbum que pertence e a que músico o álbum pertence.
SELECT TMUS AS MUSICA,TITULO AS ALBUM ,NOMEMUS AS MUSICO
FROM ALBUM A INNER JOIN MUSICO M ON 
A.IDMUS = M.IDMUS
INNER JOIN MUSICA MS ON A.IDALBUM = MS.IDALBUM


--06- Listar quais instrumentos nenhum músico toca.
SELECT NOMEINS
FROM INSTRUMENTO I LEFT JOIN TOCA T ON
I.IDINS = T.IDINS
WHERE T.IDINS IS NULL

--07- Listar nome do músico e instrumento que toca.
SELECT NOMEMUS,NOMEINS
FROM MUSICO M INNER JOIN TOCA T ON
M.IDMUS = T.IDMUS 
INNER JOIN INSTRUMENTO I ON
T.IDINS = I.IDINS

--08- Listar o nome dos músicos que não tocam instrumentos.
SELECT NOMEMUS
FROM MUSICO M LEFT JOIN TOCA T ON
M.IDMUS = T.IDMUS
WHERE T.IDMUS IS NULL



